YeniOtomasyonSistemi/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YeniOtomasyonSistemi.Models;
using YeniOtomasyonSistemi.Models.Login;

namespace YeniOtomasyonSistemi.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult _Navigation()
        {
            try
            {
                int KullaniciId = Convert.ToInt32(Session["KullaniciId"]);
                
                LidosSistemiEntities db = new LidosSistemiEntities();
                List<UserIdMenuGetir_Result> Deneme = db.UserIdMenuGetir(KullaniciId).ToList();
                
                return PartialView(Deneme);
            }
            catch (Exception)
            {
                return RedirectToAction("Login", "Security");
            }
        }
    }
}

YeniOtomasyonSistemi/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="float-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014 - @DateTime.Now.Year
    </div>
</div>

YeniOtomasyonSistemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewBag.Title | TMO-TOBB LİDAŞ</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")
    
</head>
<body class="fixed-sidebar">

    <!-- Skin configuration box -->
    <!-- @Html.Partial("_SkinConfig") -->
    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Action("_Navigation", "Shared")
      

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->
        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>

YeniOtomasyonSistemi/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>@ViewBag.Title | TMO</title>
    <!-- Iconic Fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/LoginTemplate/iconic-fonts/flat-icons/flaticon.css"/>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/LoginTemplate/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery UI -->
    <link href="~/Content/LoginTemplate/css/jquery-ui.min.css" rel="stylesheet">
    <!-- Mystic styles -->
    <link href="~/Content/LoginTemplate/css/style.css" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/favicon.ico">
</head>
<body class="ms-body ms-primary-theme">
    <!-- Preloader -->
    <div id="preloader-wrap">
        <div class="spinner spinner-8">
            <div class="ms-circle1 ms-child"></div>
            <div class="ms-circle2 ms-child"></div>
            <div class="ms-circle3 ms-child"></div>
            <div class="ms-circle4 ms-child"></div>
            <div class="ms-circle5 ms-child"></div>
            <div class="ms-circle6 ms-child"></div>
            <div class="ms-circle7 ms-child"></div>
            <div class="ms-circle8 ms-child"></div>
            <div class="ms-circle9 ms-child"></div>
            <div class="ms-circle10 ms-child"></div>
            <div class="ms-circle11 ms-child"></div>
            <div class="ms-circle12 ms-child"></div>
        </div>
    </div>

    <div class="ms-lock-screen-weather">
        <p>38&deg;</p>
        <p>Ankara, TR</p>
    </div>
    <!-- Main Content -->
    <main class="body-content ms-lock-screen">
        <!-- Body Content Wrapper -->
        @RenderBody()
    </main>
    <div class="ms-lock-screen-time">
        <p id="time"></p>
        <p id="date"></p>
    </div>
    <script type="text/javascript">
        window.onload = setInterval(clock, 1000);

        function clock() {
            var d = new Date();
            var date = d.getDate();
            var month = d.getMonth();
            var montharr = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"];
            month = montharr[month];
            var year = d.getFullYear();
            var date = d.getDate();
            var day = d.getDay();
            var dayarr = ["Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi"];
            day = dayarr[day];
            var hour = d.getHours() < 10 ? '0' + d.getHours() : d.getHours();
            var min = d.getMinutes() < 10 ? '0' + d.getMinutes() : d.getMinutes();
            var sec = d.getSeconds();
            document.getElementById("date").innerHTML = day + " " + date + " " + month + " " + year;
            document.getElementById("time").innerHTML = hour + ":" + min;
        }
    </script>
    <!-- SCRIPTS -->
    <!-- Global Required Scripts Start -->
    <script src="~/Content/LoginTemplate/js/jquery-3.5.1.min.js"></script>
    <script src="~/Content/LoginTemplate/js/popper.min.js"></script>
    <script src="~/Content/LoginTemplate/js/bootstrap.min.js"></script>
    <script src="~/Content/LoginTemplate/js/perfect-scrollbar.js"></script>
    <script src="~/Content/LoginTemplate/js/jquery-ui.min.js"></script>
    <!-- Global Required Scripts End -->
    <!-- Mystic core JavaScript -->
    <script src="~/Content/LoginTemplate/js/framework.js"></script>
    <!-- Settings -->
    <script src="~/Content/LoginTemplate/js/settings.js"></script>

</body>
</html>

YeniOtomasyonSistemi/Views/Shared/_Navigation.cshtml
@model List<YeniOtomasyonSistemi.Models.UserIdMenuGetir_Result>
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <img alt="image" class="rounded-circle" src="~/Content/LoginTemplate/img/tmo-tobb-lidas-logo.png" style="width:48px;height:48px" />
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">@Session["KullaniciAdi"]</span>
                        <span class="text-muted text-xs block">Detay <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs" style="position: absolute; top: 91px; left: 0px; will-change: top, left;">
                        <li><a class="dropdown-item" href="@Url.Action("Profil", "Account")">Profil</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Contacts", "AppViews")">Contacts</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Inbox", "Mailbox")">Mailbox</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="@Url.Action("Logout", "Security")">Çıkış</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    +
                </div>
            </li>

            @foreach (var item in Model.OrderBy(t => t.AnaMenuAdi).GroupBy(t => t.AnaMenuAdi))
            {
                <li>
                    <a href="#">
                        <i class="@item.Select(t=>t.IconAdi).FirstOrDefault()"></i>
                        <span class="nav-label">@item.Select(t => t.AnaMenuAdi).FirstOrDefault()</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level collapse ">
                        @{ string Ad = item.Key;
                            var sorgu = Model.Where(t => t.AnaMenuAdi == Ad).OrderBy(t => t.AltMenuAdi).GroupBy(t => t.AltMenuAdi).ToList();
                            foreach (var item2 in sorgu)
                            {
                                <li>
                                    <a href='@Url.Action(item2.Select(t => t.ActionAdi).FirstOrDefault(), item2.Select(t => t.ControllerAdi).FirstOrDefault())'>
                                        @item2.Select(t => t.AltMenuAdi).FirstOrDefault()
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </li>
            }
        </ul>
    </div>
</nav>

YeniOtomasyonSistemi/Views/Shared/_SkinConfig.cshtml
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-settings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                <span>
                    Collapse menu
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed sidebar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar v.2
                    <br />
                    <small>*Primary layout</small>
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar2" class="onoffswitch-checkbox" id="fixednavbar2">
                        <label class="onoffswitch-label" for="fixednavbar2">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Boxed layout
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed footer
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-0">
                        Default
                    </a>
                </span>
            </div>
            <div class="setings-item blue-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-1">
                        Blue light
                    </a>
                </span>
            </div>
            <div class="setings-item yellow-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-3">
                        Yellow/Purple
                    </a>
                </span>
            </div>
            <div class="setings-item ultra-skin">
                <span class="skin-name ">
                    <a target="_blank" href="md_skin/" class="md-skin">
                        Material Design
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

YeniOtomasyonSistemi/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li style="padding:20px">
                <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext"></span>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="#" class="float-left">
                                <img alt="image" class="rounded-circle" src="~/Images/a7.jpg">
                            </a>
                            <div class="media-body">
                                <small class="float-right">46h ago</small>
                                <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="#" class="float-left">
                                <img alt="image" class="rounded-circle" src="~/Images/a4.jpg">
                            </a>
                            <div class="media-body ">
                                <small class="float-right text-navy">5h ago</small>
                                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="#" class="float-left">
                                <img alt="image" class="rounded-circle" src="~/Images/profile.jpg">
                            </a>
                            <div class="media-body ">
                                <small class="float-right">23h ago</small>
                                <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#">
                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                <span class="float-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="float-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="float-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("Logout", "Security")">
                    <i class="fa fa-sign-out"></i> Çıkış
                </a>
            </li>
            <li>
                <a class="right-sidebar-toggle">
                    <i class="fa fa-tasks"></i>
                </a>
            </li>
        </ul>
    </nav>
</div>

YeniOtomasyonSistemi/Views/Shared/_TopNavbar2.cshtml
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-expand-lg navbar-static-top" role="navigation">
        <a href="#" class="navbar-brand">Inspinia</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-reorder"></i>
        </button>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav mr-auto">
                <li class="active">
                    <a aria-expanded="false" role="button" href="@Url.Action("Index", "Layouts")"> Back to main Layout page</a>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item</a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item</a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item</a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item</a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                        <li><a href="">Menu item</a></li>
                    </ul>
                </li>

            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="login.html">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>