YeniOtomasyonSistemi/Controllers/LaboratuvarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YeniOtomasyonSistemi.Models.Login;
using YeniOtomasyonSistemi.Models;
using static YeniOtomasyonSistemi.Models.KayisiLaboratuvarMetodlari;

namespace YeniOtomasyonSistemi.Controllers
{
    [ControlLogin]
    public class LaboratuvarController : Controller
    {
        // GET: Laboratuvar
        [Authorize(Roles = "NumuneAlmaListesi")]
        [HttpGet]
        public ActionResult NumuneAlmaListesi()
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            string KullaniciAdi = Session["KullaniciAdi"].ToString();
            string SubeKodu = Session["KullaniciSubeKodu"].ToString();
            int SubeId = Convert.ToInt32(Session["KullaniciSubeId"].ToString());
            var NumuneListesi = db.LabNumuneAlma.Where(t => t.KaydedenSubesi == SubeKodu && t.KayitZamani == DateTime.Today).ToList();
            var Gorevliler = db.TanGorevliler.Where(t => t.GorevliSubeId == SubeId&&t.GorevBirimi== "Numune Alma").ToList(); // Numune alan görevli ile kaydeden görevli bazı durum
            return View(Tuple.Create(NumuneListesi, Gorevliler));

        }

        [Authorize(Roles = "NumuneAlmaListesi")]
        [HttpPost]
        public ActionResult NumuneAlmaListesi(DateTime tarih)
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            string KullaniciAdi = Session["KullaniciAdi"].ToString();
            string SubeKodu = Session["KullaniciSubeKodu"].ToString();
            int SubeId = Convert.ToInt32(Session["KullaniciSubeId"].ToString());
            var NumuneListesi = db.LabNumuneAlma.Where(t => t.KaydedenSubesi == SubeKodu && t.KayitZamani >= tarih).ToList();
            var Gorevliler = db.TanGorevliler.Where(t => t.GorevliSubeId == SubeId && t.GorevBirimi == "Numune Alma").ToList(); // Numune alan görevli ile kaydeden görevli bazı durum
            return View(Tuple.Create(NumuneListesi, Gorevliler));

        }

        [Authorize(Roles = "NumuneAlmaListesi")]
        [HttpPost]
        public ActionResult NumuneAlmaKaydet(int id,string MuhurNo,string NumuneAlinmaYeri,string AmbalajSekli,string NumuneAgirlik,string NumuneAdet,string Gorevli)
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            string KullaniciAdi = Session["KullaniciAdi"].ToString();
            string SubeKodu = Session["KullaniciSubeKodu"].ToString();
            int GorevliId = db.TanGorevliler.Where(t => t.GorevliAdiSoyadi == Gorevli).Select(t => t.GorevliId).FirstOrDefault();
            var na = db.LabNumuneAlma.Where(t => t.NumuneId == id).FirstOrDefault();
            na.AmbalajAdeti = NumuneAdet;
            na.AmbalajSekli = AmbalajSekli;
            na.DegisiklikZamani = DateTime.Now;
            na.DegistirenPersonel = KullaniciAdi;
            na.KaydedenPersonel = KullaniciAdi;
            na.KaydedenSubesi = SubeKodu;
            na.KayitDurumu = "Tamamlandı";      
            na.NumuneAgirligi = NumuneAgirlik;
            na.NumuneAlindigiYer = NumuneAlinmaYeri;
            na.NumuneMuhurNo = MuhurNo;
            na.NumuneyiAlanGorevliId = GorevliId;
            db.SaveChanges();

            var NumuneBilgileri = db.LabNumuneAlma.Where(t => t.NumuneId == id).FirstOrDefault();
            LabLaboratuvarAnalizListesi lb = new LabLaboratuvarAnalizListesi();
            var SonAnalizNumarasi = db.LabLaboratuvarAnalizListesi.Where(t => t.SubeKodu == SubeKodu).OrderByDescending(t => t.LabAnalizId).Select(t => t.AnalizNo).FirstOrDefault();
            string UrunAdi = NumuneBilgileri.KantarTartimKayitlari.AractakiUrun;
            int UrunGurubuId = db.TanUrunUstGuruplari.Where(t => t.UrunUstGurupAdi == UrunAdi).Select(t=>t.UrunUstGurupKoduId).FirstOrDefault();
            if (SonAnalizNumarasi != null)
            {
                int AnalizN = Convert.ToInt32(SonAnalizNumarasi);
                lb.AnalizNo = (AnalizN + 1).ToString();
            }
            else
            {
                lb.AnalizNo = "1";
            }
            lb.AnalizTarihi = DateTime.Now;
            lb.Durumu = "Beklemede";
            lb.KantarKayitNo = NumuneBilgileri.KantarTartimKayitlari.KantarKayitNo.ToString();
            lb.KaydedenUser = KullaniciAdi;
            lb.KayitTarihi = DateTime.Now;
            lb.NumuneNo = NumuneBilgileri.NumuneNo.ToString();
            lb.SubeKodu = SubeKodu;
            lb.UrunUstGurubuId = UrunGurubuId;
            db.LabLaboratuvarAnalizListesi.Add(lb);
            db.SaveChanges();
            return RedirectToAction("NumuneAlmaListesi");

        }

        [Authorize(Roles = "LaboratuvarAnalizListesi")]
        [HttpGet]
        public ActionResult LaboratuvarAnalizListesi()
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            string KullaniciAdi = Session["KullaniciAdi"].ToString();
            string SubeKodu = Session["KullaniciSubeKodu"].ToString();
            int SubeId = Convert.ToInt32(Session["KullaniciSubeId"].ToString());
            DateTime Yarin = DateTime.Now.AddDays(1);
            DateTime Dun = DateTime.Now.AddDays(-1);

            var AnalizListesi = db.LabLaboratuvarAnalizListesi.Where(t => t.SubeKodu == SubeKodu && t.KayitTarihi >= Dun && t.KayitTarihi <= Yarin).ToList();
            var Gorevliler = db.TanGorevliler.Where(t => t.GorevliSubeId == SubeId && t.GorevBirimi == "Numune Alma").ToList(); // Numune alan görevli ile kaydeden görevli bazı durum
            return View(Tuple.Create(AnalizListesi, Gorevliler));

        }

        [Authorize(Roles = "LaboratuvarAnalizListesi")]
        [HttpPost]
        public ActionResult LaboratuvarAnalizListesi(DateTime tarih)
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            string KullaniciAdi = Session["KullaniciAdi"].ToString();
            string SubeKodu = Session["KullaniciSubeKodu"].ToString();
            int SubeId = Convert.ToInt32(Session["KullaniciSubeId"].ToString());
            var vAnalizListesi = db.LabLaboratuvarAnalizListesi.Where(t => t.SubeKodu == SubeKodu && t.KayitTarihi >= tarih).ToList();
            var Gorevliler = db.TanGorevliler.Where(t => t.GorevliSubeId == SubeId && t.GorevBirimi == "Numune Alma").ToList(); // Numune alan görevli ile kaydeden görevli bazı durum
            return View(Tuple.Create(vAnalizListesi, Gorevliler));

        }

        [Authorize(Roles = "LaboratuvarAnalizListesi")]
        [HttpGet]
        public ActionResult LaboratuvarKayisiAnalizi(int id)
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            string KullaniciAdi = Session["KullaniciAdi"].ToString();
            string SubeKodu = Session["KullaniciSubeKodu"].ToString();
            int SubeId = Convert.ToInt32(Session["KullaniciSubeId"].ToString());
            var Sorgu = db.LabKayisiAnalizDetaylari.Where(t => t.AnalizListeId == id&&t.SubeKodu==SubeKodu).FirstOrDefault();
            var AnalizGenelBilgileri = db.LabLaboratuvarAnalizListesi.Where(t => t.SubeKodu == SubeKodu && t.LabAnalizId == id).FirstOrDefault();
            if (Sorgu!=null)
            {
                AnalizKalemleri ak = new AnalizKalemleri();
                ak.AgirKirliTane =Convert.ToDecimal( Sorgu.AgirKirliTane);
                ak.BocekHasarli = Convert.ToDecimal(Sorgu.BocekHasarli);
                ak.CekirdekliKayisi= Convert.ToDecimal(Sorgu.CekirdekliKayisi);
                ak.CilliTane= Convert.ToDecimal(Sorgu.CilliTane); 
                ak.DoluYaraliTane= Convert.ToDecimal(Sorgu.DoluYaraliTane);
                ak.GunesYanigi= Convert.ToDecimal(Sorgu.GunesYanigi);
                ak.HafifKirliTane= Convert.ToDecimal(Sorgu.HafifKirliTane);
                ak.HasarliTane= Convert.ToDecimal(Sorgu.HasarliTane);
                ak.KukurtOrani = Convert.ToInt32(Sorgu.KukurtOrani);
                ak.OluBocekParcalari= Convert.ToDecimal(Sorgu.OluBocekParcalari);
                ak.RenkUyumsuzlugu = Convert.ToDecimal(Sorgu.RenkUyumsuzlugu);
                ak.RutubetOrani= Convert.ToDecimal(Sorgu.RutubetOrani);
                ak.TaneAdeti= Convert.ToInt32(Sorgu.TaneAdeti);
                ak.YabanciMaddeBitkisel= Convert.ToDecimal(Sorgu.YabanciMaddeBitkisel);
                ak.YabanciMaddeTehlikeli= Convert.ToDecimal(Sorgu.YabanciMaddeTehlikeli);
                ak.AnalizListesiId = id;
                
                AnalizSonuclari Ans = new AnalizSonuclari();
                Ans.BoyDerecesi = Convert.ToInt32(Sorgu.SonucBoyDerecesi);
                Ans.GurupAdi = Sorgu.SonucGurupAdi;
                Ans.KayisiKukurtTipi = Sorgu.SonucKayisiKukurtTipi;
                Ans.RedEdilmeNedeni = Sorgu.SonucRedEdilmeAciklamasi;
                Ans.ToplamKusur = Convert.ToDecimal(Sorgu.SonucToplamKusur);
                AnalizSonucuCikanUrunBilgileri analiz = new AnalizSonucuCikanUrunBilgileri();
                analiz.ISINKODU = Sorgu.SonucUrunISINKODU;
                analiz.UrunAdi = Sorgu.SonucUrunAdi;
                analiz.UrunKodu = Sorgu.SonucUrunKodu;
                return View(Tuple.Create(ak, Ans,analiz, AnalizGenelBilgileri));
            }
            else
            {
                AnalizKalemleri ak = new AnalizKalemleri();
                ak.AnalizListesiId = id;
                AnalizSonuclari Ans = new AnalizSonuclari();
                AnalizSonucuCikanUrunBilgileri analizUrun = new AnalizSonucuCikanUrunBilgileri();
                return View(Tuple.Create(ak, Ans,analizUrun, AnalizGenelBilgileri));
            }
            

        }
        [Authorize(Roles = "LaboratuvarAnalizListesi")]
        [HttpPost]
        public ActionResult LaboratuvarKayisiAnalizi(AnalizKalemleri ak)
        {
            try
            {
                string SubeKodu = Session["KullaniciSubeKodu"].ToString();
                LidosSistemiEntities db = new LidosSistemiEntities();
                int id = ak.AnalizListesiId;

YeniOtomasyonSistemi/Views/Laboratuvar/LaboratuvarAnalizListesi.cshtml
@model Tuple<List<YeniOtomasyonSistemi.Models.LabLaboratuvarAnalizListesi>, List<YeniOtomasyonSistemi.Models.TanGorevliler>>
@{
    ViewBag.Title = "Laboratuvar Analiz Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="color:orange;text-align:center;">TMO-TOBB LİSANSLI DEPOCULUK A.Ş</h2>
<h4 style="color:green;text-align:center;">Analiz Kaydı Listesi</h4>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title" style="height:65px">
                    @using (Html.BeginForm("LaboratuvarAnalizListesi", "Laboratuvar", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <div class="form-group" style="float:left;">
                            <div class="input-group date col-lg-12">
                                <input type="date" class="form-control" disabled value="@String.Format("{0:yyyy-MM-dd}", DateTime.Now)">
                                <input type="date" class="form-control" name="tarih">
                                <div class="input-group col-lg-4">
                                    <button type="submit" class="btn btn-outline-info">
                                        <i class="fa fa-calendar"></i> Filtrele
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <br />
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>Analiz No</th>
                                <th>Tarih</th>
                                <th>Numune No</th>
                                <th>Kantar No</th>
                                <th>Ürün Kodu </th>
                                <th>Ürün Adı</th>

                                <th>Durum</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.Item1)
                            {

                                string color = "";
                                if (item.Durumu == "Beklemede")
                                {

                                    color = "lightyellow";
                                }
                                else if (item.Durumu == "Tamamlandı")
                                {

                                    color = "#ceff8f";
                                }
                                else if (item.Durumu == "RedEdildi")
                                {

                                    color = "#f8c9c9";
                                }
                                <tr style="background-color:@color;">
                                    <td>@item.AnalizNo</td>
                                    <td>@item.AnalizTarihi.ToString().Substring(0, 10)</td>
                                    <td>@item.NumuneNo</td>
                                    <td>@item.KantarKayitNo</td>
                                    <td>@item.TanUrunUstGuruplari.UrunUstGurupKodu</td>
                                    <td>@item.TanUrunUstGuruplari.UrunUstGurupAdi</td>


                                    @if (item.Durumu == "Beklemede")
                                    {
                                        <td>
                                            @if (item.UrunUstGurubuId == 5)
                                            {
                                                <a href='@Url.Action("LaboratuvarKayisiAnalizi","Laboratuvar",new { id=item.LabAnalizId})' class="btn btn-outline btn-warning">Analiz Yap</a>
                                            }
                                            else
                                            {
                                                <a href="" class="btn btn-outline btn-warning"></a>
                                            }

                                        </td>
                                        <td>
                                            <button class="btn btn-warning btn-circle" type="button" title="Bildir">
                                                <i class="fa fa-warning"></i>
                                            </button>
                                        </td>
                                    }
                                    else if (item.Durumu == "Tamamlandı")
                                    {
                                        <td style="text-align:center;"> <button class="btn btn-primary" type="button"><i class="fa fa-check"></i> Tamamlandı</button></td>
                                        <td>

                                            <a class="btn  btn-danger" href='@Url.Action("LaboratuvarKayisiAnaliziYazdir","Laboratuvar",new { id=item.LabAnalizId})' target="_blank" title="Yazdır">
                                                <i class="fa fa-print" style="color:white;"></i>
                                            </a>
                                            <a class="btn  btn-success" href='@Url.Action("LaboratuvarKayisiAnalizi","Laboratuvar",new { id=item.LabAnalizId})' title="Yeniden Analiz Yap">
                                                <i class="fa fa-refresh" style="color:white;"></i>
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td> <button type="button" class="btn btn-outline btn-danger">Red Edildi</button></td>
                                        <td>
                                            <a class="btn  btn-danger" href='@Url.Action("LaboratuvarKayisiAnaliziYazdir","Laboratuvar",new { id=item.LabAnalizId})' target="_blank" title="Yazdır">
                                                <i class="fa fa-print" style="color:white;"></i>
                                            </a>
                                            <a class="btn  btn-success" href='@Url.Action("LaboratuvarKayisiAnalizi","Laboratuvar",new { id=item.LabAnalizId})' title="Yeniden Analiz Yap">
                                                <i class="fa fa-refresh" style="color:white;"></i>
                                            </a>
                                        </td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")

    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")

    @Styles.Render("~/plugins/dataPickerStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/typehead")

    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/dataPicker")

    @Scripts.Render("~/plugins/clockpicker")
    @Scripts.Render("~/plugins/dateRange")

    <script type="text/javascript">
        $(document).ready(function () {

            $('.dataTables-example').DataTable({

                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'MudiKaydiListesi' },
                    { extend: 'pdf', title: 'MudiKaydiListesi' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });
        });
    </script>

}

YeniOtomasyonSistemi/Views/Laboratuvar/LaboratuvarKayisiAnaliziYazdir.cshtml
@model YeniOtomasyonSistemi.Models.LabKayisiAnalizDetaylari
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    @{
        string SubeKodu = Session["KullaniciSubeKodu"].ToString();
        YeniOtomasyonSistemi.Models.LidosSistemiEntities db = new YeniOtomasyonSistemi.Models.LidosSistemiEntities();
        int KayitNo = Convert.ToInt32(Model.LabLaboratuvarAnalizListesi.KantarKayitNo);
        var MudiBilgileri = db.KantarTartimKayitlari.Where(t => t.KantarKayitNo == KayitNo&&t.KaydedenSube==SubeKodu).FirstOrDefault();
    }
    <div class="container">
        <div class="card">
            <div class="card-header">
                Analiz No : @Model.LabLaboratuvarAnalizListesi.AnalizNo
                <span class="float-right"> <strong>Durum:</strong> @Model.LabLaboratuvarAnalizListesi.Durumu</span>
                <br />
                <strong style="text-align:center;">Tarih : @Model.KayitZamani.ToString().Substring(0, 10)</strong>
                <span class="float-right"> <strong>Lisanslı Depo Adı :</strong> TMO-TOBB LİDAŞ (Malatya Şubesi)</span>
            </div>
            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <h6 class="mb-3">Yetki Sınıflandırıcı:</h6>
                        <div>
                            <strong>Malatya Ticaret Borsası Laboratuvarı</strong>
                        </div>
                        <div>İsmetiye Mh. Buhara Cd.</div>
                        <div>Yeni Mektep Sk. No:181/A </div>
                        <div>Battalgazi/MALATYA</div>

                    </div>

                    <div class="col-sm-6">
                        <h6 class="mb-3">Mudi Bilgileri:</h6>
                        <div>
                            <strong></strong>
                        </div>
                        <div>TC / VKN : @MudiBilgileri.KantarMudiBilgileri.MudiTcVkn</div>
                        <div>Adı Soyadı : @MudiBilgileri.KantarMudiBilgileri.MudiAdiSoyadi</div>
                        <div>Adres : @MudiBilgileri.KantarMudiBilgileri.AdresDevami</div>
                        <div>İl / İlçe : @MudiBilgileri.KantarMudiBilgileri.AdresIl / @MudiBilgileri.KantarMudiBilgileri.AdresIlce</div>
                        <div>İletişim : @MudiBilgileri.KantarMudiBilgileri.Telefon</div>
                    </div>



                </div>
                @if (Model.SonucRedVarmi == "Hayır")
                {
                    <div class="table-responsive-sm">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="center">Analiz Sonuç Adı</th>
                                    <th class="right">Tespit Edilen Değerler</th>
                                    <th class="center"></th>
                                    <th class="right"></th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="center"><b>1- </b>ÜRÜN ADI</td>
                                    <td class="right">@Model.SonucUrunAdi</td>
                                    <td></td>
                                    <td></td>

                                </tr>
                                <tr>
                                    <td class="center"><b>2- </b>ÜRÜN KODU</td>
                                    <td class="right">@Model.SonucUrunKodu</td>
                                    <td class="center"><b>4- </b>Gurup</td>
                                    <td class="right">@Model.SonucGurupAdi</td>
                                </tr>
                                <tr>
                                    <td class="center"><b>3- </b>ÜRÜN ISINKODU</td>
                                    <td class="right">@Model.SonucUrunISINKODU</td>
                                    <td class="center"><b>5- </b>Sınıfı</td>
                                    <td class="right">@Model.SonucBoyDerecesi</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="table-responsive-sm">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="center">Analiz Sonuç Adı</th>
                                    <th class="right">Tespit Edilen Değer</th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="center"><b>Ürün İş Yeri Tarafından Red Edilmiştir </b></td>
                                    <td class="right"><i style="color:red;">@Model.SonucRedEdilmeAciklamasi</i></td>

                                </tr>

                            </tbody>
                        </table>
                    </div>
                }
                <hr />
                <div class="table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="center">Yapılan Analizin Adı</th>
                                <th class="right">Çıkan Sonuç</th>
                                <th class="center">Yapılan Analizin Adı</th>
                                <th class="right">Çıkan Sonuç</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="center"><b>1- </b>1000 Gramdaki Tane Adeti</td>
                                <td class="right">@Model.TaneAdeti</td>
                                <td class="center"><b>10- </b>Renk Uyumsuzluğu (%)</td>
                                <td class="right">@Model.RenkUyumsuzlugu</td>
                            </tr>
                            <tr>
                                <td class="center"><b>2- </b>Rutubet (%) (TS EN 15948)</td>
                                <td class="right">@Model.RutubetOrani</td>
                                <td class="center"><b>11- </b>Çekirdekli Kayısı</td>
                                <td class="right">@Model.CekirdekliKayisi</td>
                            </tr>
                            <tr>
                                <td class="center"><b>3- </b>Ağır Kirli Tane (%)</td>
                                <td class="right">@Model.AgirKirliTane</td>
                                <td class="center"><b>12- </b>Böcek Hasarlı (%)</td>
                                <td class="right">@Model.BocekHasarli</td>
                            </tr>
                            <tr>
                                <td class="center"><b>4- </b>Hafif Kirli Tane (%)</td>
                                <td class="right">@Model.HafifKirliTane</td>
                                <td class="center"><b>13- </b>Ölü Böcek ve Parçaları (%)</td>
                                <td class="right">@Model.OluBocekParcalari</td>
                            </tr>
                            <tr>
                                <td class="center"><b>5- </b>Hasarlı Tane, Parça, Ezik vb.(%)</td>
                                <td class="right">@Model.HasarliTane</td>
                                <td class="center"><b>14- </b>Yabancı Madde Bitkisel (%)</td>
                                <td class="right">@Model.YabanciMaddeBitkisel</td>
                            </tr>
                            <tr>
                                <td class="center"><b>6- </b>Çilli Tane (%)</td>
                                <td class="right">@Model.CilliTane</td>
                                <td class="center"><b>15- </b>Yabancı Madde Tehlikeli (%)</td>
                                <td class="right">@Model.YabanciMaddeTehlikeli</td>
                            </tr>
                            <tr>
                                <td class="center"><b>7- </b>Dolu Yaralı Tane (%)</td>
                                <td class="right">@Model.DoluYaraliTane</td>
                                <td class="center"><b>16- </b>TOPLAM KUSUR ORANI (%)</td>
                                <td class="right">@Model.SonucToplamKusur</td>
                            </tr>
                            <tr>
                                <td class="center"><b>8- </b>Güneş Yanığı (%)</td>
                                <td class="right">@Model.GunesYanigi</td>
                                <td class="center"><b>17- </b>KÜKÜRT ORANI (%)</td>
                                <td class="right">@Model.KukurtOrani ppm</td>
                            </tr>
                            <tr>
                                <td class="center"><b>9- </b>İlaçlı</td>
                                <td class="right">HAYIR</td>
                                <td class="center"><b>18- </b>Haşereli</td>
                                <td class="right">HAYIR</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <small>
                    ** Yapılan analiz sonucunda yukarıdaki değer tespit edilmiş olup bunlar tek başına veya ayrı olarak kullanılmaz .
                    Analizlerde kullanılan cihaz ve ekipmanların periyodik kalibrasyon kontrolleri yapılmaktadır.
                </small>

                <div class="table-responsive-sm">
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="width:35%;"></th>
                                <th style="width:30%;"></th>
                                <th style="width:35%;"></th>
                            </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td class="center">Analizi Yapan</td>
                                <td class="left">AYDA GÜLDAŞ</td>
                                <td class="left">İmzası</td>
                            </tr>
                            <tr>
                                <td class="center">Analizi Onaylayan</td>
                                <td class="left"> </td>
                                <td class="left">İmzası</td>
                            </tr>
                            <tr>
                                <td class="center">Lisanslı Depo Sorumlusu</td>
                                <td class="left">ALİ ÇAKAR</td>
                                <td class="left">İmzası</td>
                            </tr>
                            <tr>
                                <td class="center">Mudi</td>
                                <td class="left">@MudiBilgileri.KantarMudiBilgileri.MudiAdiSoyadi</td>
                                <td class="left">İmzası</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <small>
                    Analiz sınıflandırma belgesi 5300 Sayılı Kanun ve İlgili Yönetmelik kapsamında yetkili sınıflandırıcı tarafından verilmiştir .
                    Not: Analiz sonuçları kabul edilmişse mudi tarafından imzalanacaktır. Kabul edilmemişse "Analizi Kabul Etmiyorum" şerhi yazılarak mudice imzalanacaktır.
                </small>
            </div>
        </div>
    </div>
    <script type="text/javascript">

        window.addEventListener("load", window.print());
    </script>
</body>

</html>