YeniOtomasyonSistemi/Models/Login/ControlLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace YeniOtomasyonSistemi.Models.Login
{
    public class ControlLogin:ActionFilterAttribute,IActionFilter
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            try
            {
                if (!string.IsNullOrEmpty(HttpContext.Current.Session["KullaniciId"].ToString()))
                {
                    base.OnActionExecuting(filterContext);
                }
                else
                {
                    HttpContext.Current.Response.Redirect("/Security/Login");
                }
            }
            catch (Exception)
            {
                HttpContext.Current.Response.Redirect("/Security/Login");
            }
        }
    }
}

YeniOtomasyonSistemi/Models/Login/LoginState.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YeniOtomasyonSistemi.Models.Login
{
    public class LoginState
    {
        public LoginState()
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
        }

        public bool IsLoginSuccess(string user,string pwd)
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            LKullanicilar resultUser = db.LKullanicilar.Where(x => x.KullaniciAdi.Trim().ToString().Equals(user) && x.KullaniciSifresi.Equals(pwd)).FirstOrDefault();
            if (resultUser != null)
            {
                LSubeler SubeBilgisi = resultUser.LSubeler;
                HttpContext.Current.Session.Add("KullaniciId", resultUser.KullaniciId);
                HttpContext.Current.Session.Add("KullaniciAdi", resultUser.KullaniciAdi);
                HttpContext.Current.Session.Add("KullaniciSubeId", resultUser.KullaniciSubesi);
                HttpContext.Current.Session.Add("KullaniciSubeKodu", SubeBilgisi.SubeKisaKodu);
                return true;
            }
            return new bool();
        }
    }
}

YeniOtomasyonSistemi/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using YeniOtomasyonSistemi.Models;
using YeniOtomasyonSistemi.Models.Login;

namespace YeniOtomasyonSistemi.Controllers
{
    public class SecurityController : Controller
    {
        // GET: Security
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LKullanicilar kullanicilar)
        {
            LidosSistemiEntities db = new LidosSistemiEntities();
            if (new LoginState().IsLoginSuccess(kullanicilar.KullaniciAdi, kullanicilar.KullaniciSifresi))
            {
                FormsAuthentication.SetAuthCookie(Convert.ToString(Session["KullaniciId"]), false);
                return RedirectToAction("Index", "Home");
            }
            TempData["message"] = "Kullanıcı adınız veya şifreniz yanlış!";
            return RedirectToAction("Login");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            Response.Cookies[".ASPXAUTH"].Expires = DateTime.Now.AddDays(-1);
            return RedirectToAction("Login");
        }
    }
}

YeniOtomasyonSistemi/Views/Security/Login.cshtml
@model YeniOtomasyonSistemi.Models.LKullanicilar
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<div class="ms-content-wrapper">
    <img class="ms-user-img ms-img-round ms-lock-screen-user" src="~/Content/LoginTemplate/img/tmo-tobb-lidas-logo.png" alt="people">
    <h1>TMO - TOBB LİDAŞ</h1>
    <p style="font-size:14px; color:red; padding-bottom:10px">@TempData["message"]</p>
    @using (Html.BeginForm("Login", "Security", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="ms-form-group my-0 mb-0 has-icon fs-14" style="padding-bottom:10px">
            <input type="text" class="ms-form-input" name="KullaniciAdi" placeholder="Kullanıcı Adınız" value="" required aria-required="true">
            <i class="material-icons">security</i>
        </div>
        <div class="ms-form-group my-0 mb-0 has-icon fs-14">
            <input type="password" class="ms-form-input" name="KullaniciSifresi" placeholder="Parola" value="" required aria-required="true">
            <i class="material-icons">security</i>
        </div>
        <button type="submit" class="btn btn-success w-100">Giriş</button>
    }

</div>